### PR TITLE
various updates

### PR DESCRIPTION
**Pull request by dg0tm**
I think it should be reimported.

visit https://github.com/dl5di/OpenDV/commit/bf442753083b1ff9689a4bf2a57558e6f84c7eec#diff-48b5bf4431d1bb922483f2c050bff1ee

Secoundly i read and tweak the makefiles, one more.

### CODE REVIEW

**Comment by dg0tm** [comment]
@g4klx Have you time to judge the PR?

**Comment by dg0tm** [comment]
@g4klx any thoughts on that?

**Comment by g4klx** [comment]
Silly idea. Leave it it as it is. It has different behaviour on Windows and Linux and that isn't acceptable.

**Comment by dg0tm** [comment]
@g4klx any thoughts on that or can you finally judge?

**Pull request closed without merging**
